#!/bin/bash
cd "${0%/*}" || exit
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions
#------------------------------------------------------------------------------

cleanCase

rm -rf \
0 \
./preCICE-output/ \
./precice-*-iterations.log \
./precice-*-convergence.log \
./precice-*-events.json \
./precice-*-events-summary.log \
./precice-postProcessingInfo.log \
./precice-*-watchpoint-*.log \
./precice-*-watchintegral-*.log \
./core \
./postProcessing \
./proc* \
log.* \
*.json \
*.log

#------------------------------------------------------------------------------
