#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------
# mesh creation
sed -i "s/^\s\{0,\}blocks\s\{1,\}.*/blocks $1;/g" system/blockMeshDict
sed -i "s/^\s\{0,\}numberOfSubdomains\s\{1,\}.*/numberOfSubdomains $2;/g" system/decomposeParDict		
sed -i "s/^\s\{0,\}n\s\{1,\}.*/n ($2 1 1);/g" system/decomposeParDict
sed -i "s/^\s\{0,\}endTime\s\{1,\}.*/endTime  $3;/g" system/controlDict

runApplication blockMesh
runApplication transformPoints -translate '(-0.2 -0.2 0)' 
runApplication topoSet
runApplication createPatch -overwrite

# set inlet velocity
cp -r 0.org 0
runApplication setExprBoundaryFields

# decompose and run case
runApplication decomposePar
runParallel renumberMesh -overwrite
runParallel $(getApplication)

#------------------------------------------------------------------------------
