#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

# dummy file for post-processing with paraview
touch case.foam
touch case.OpenFOAM

# mesh creation
runApplication blockMesh
runApplication transformPoints -translate '(-0.2 -0.2 0)' 
runApplication topoSet
runApplication createPatch -overwrite

# set inlet velocity
cp -r 0.org 0
runApplication setExprBoundaryFields

# decompose and run case
runApplication decomposePar
runParallel renumberMesh -overwrite
runParallel $(getApplication)

#------------------------------------------------------------------------------
